import { esc, icon, avatar, statusBadge, fmtDateTime, refreshIcons, emptyState, on, download } from '../ui.js';

const TYPE_LABELS = {
  task_created: 'Task queued', task_started: 'Task started', script_started: 'Script started', script_completed: 'Script completed', ai_message: 'AI reasoning',
  tool_call: 'Tool call', tool_result: 'Tool result', tool_error: 'Tool error', tool_blocked: 'Permission blocked', tool_rejected: 'Action rejected',
  approval_requested: 'Approval requested', approval_resolved: 'Approval resolved', escalation: 'Escalation', decision: 'AI decision',
  task_completed: 'Task completed', task_failed: 'Task failed', task_cancelled: 'Task cancelled', task_paused: 'Task paused', task_needs_attention: 'Needs attention',
  config_changed: 'Configuration', employee_created: 'Employee created', employee_status: 'Employee status', notification: 'Notification',
};

export function activityTable(rows, empById, { showEmployee = true } = {}) {
  if (!rows.length) return emptyState('activity', 'No activity yet', 'Every script execution, tool call, decision and approval is logged here as it happens.');
  return `<div class="table-wrap"><table class="log-table"><thead><tr><th style="width:150px">Time</th>${showEmployee ? '<th>Employee</th>' : ''}<th>Event</th><th>Script</th><th>Tool</th><th style="width:130px">Status</th></tr></thead><tbody>
    ${rows.map((a) => `<tr class="clickable" data-act="${a.id}">
      <td class="muted small">${fmtDateTime(a.ts)}</td>
      ${showEmployee ? `<td><div class="row gap-6">${empById[a.employeeId] ? avatar(empById[a.employeeId], 'avatar-sm') : ''}<span class="small">${esc(empById[a.employeeId]?.name || '—')}</span>${a.origin === 'extension' ? `<span class="badge badge-info" title="Ran in the browser extension">${icon('puzzle')}</span>` : ''}</div></td>` : ''}
      <td><div class="tiny muted">${esc(TYPE_LABELS[a.type] || a.type)}</div><div class="small">${esc(String(a.message || '').slice(0, 220))}</div></td>
      <td class="small">${esc(a.scriptName || '')}</td>
      <td>${a.tool ? `<span class="tag">${esc(a.tool)}</span>` : ''}</td>
      <td>${statusBadge(a.status || 'info')}</td>
    </tr>`).join('')}
  </tbody></table></div>`;
}

export function bindActivityRows(root, rows, span = 6) {
  root._actRows = Object.fromEntries(rows.map((r) => [r.id, r]));
  root._actSpan = span;
  if (root._actBound) return;
  root._actBound = true;
  on(root, 'click', 'tr[data-act]', (e, tr) => {
    const next = tr.nextElementSibling;
    if (next?.classList.contains('log-detail')) { next.remove(); return; }
    const a = root._actRows[tr.dataset.act];
    if (!a) return;
    const span = root._actSpan;
    const d = document.createElement('tr');
    d.className = 'log-detail';
    d.innerHTML = `<td colspan="${span}"><div class="col">
      <div class="small">${esc(a.message)}</div>
      ${a.input ? `<div><div class="tiny muted strong mb-8">Input</div><pre class="light">${esc(a.input)}</pre></div>` : ''}
      ${a.output ? `<div><div class="tiny muted strong mb-8">Output</div><pre class="light">${esc(a.output)}</pre></div>` : ''}
      ${a.error ? `<div class="callout danger">${icon('alert-triangle')}<div class="small">${esc(a.error)}</div></div>` : ''}
      <div class="row small muted wrap">${a.taskId ? `<a href="#/tasks/${a.taskId}">${icon('list-checks')} Open task</a>` : ''}${a.approvalId ? `<a href="#/approvals">${icon('shield-check')} Approval</a>` : ''}${a.durationMs ? `<span>${a.durationMs} ms</span>` : ''}<span>Origin: ${esc(a.origin || 'app')}</span><span class="mono">${esc(a.id)}</span></div>
    </div></td>`;
    tr.after(d);
    refreshIcons();
  });
}

export default async function activity(ctx) {
  const { el, app } = ctx;
  const f = { employee: '', type: '', status: '', q: '' };
  let limit = 200;
  el.innerHTML = '<div class="page" id="act-page"></div>';
  const page = el.querySelector('#act-page');
  const render = async () => {
    if (!ctx.isCurrent()) return;
    const [all, employees] = await Promise.all([app.db.all('activity'), app.db.all('employees')]);
    const empById = Object.fromEntries(employees.map((e) => [e.id, e]));
    const rows = all.filter((a) => (!f.employee || a.employeeId === f.employee) && (!f.type || a.type === f.type) && (!f.status || a.status === f.status)
      && (!f.q || `${a.message} ${a.tool || ''} ${a.scriptName || ''}`.toLowerCase().includes(f.q.toLowerCase()))).sort((a, b) => b.ts - a.ts);
    page.innerHTML = `<div class="page-head"><div><h1>Activity</h1><p>Audit log generated by real executions — scripts, tools, inputs, outputs, decisions, errors and approvals.</p></div><button class="btn" id="export">${icon('download')} Export</button></div>
      <div class="row wrap mb-16">
        <select class="select" style="width:180px" data-f="employee"><option value="">All employees</option>${employees.map((e) => `<option value="${e.id}" ${f.employee === e.id ? 'selected' : ''}>${esc(e.name)}</option>`).join('')}</select>
        <select class="select" style="width:190px" data-f="type"><option value="">All events</option>${Object.entries(TYPE_LABELS).map(([k, v]) => `<option value="${k}" ${f.type === k ? 'selected' : ''}>${v}</option>`).join('')}</select>
        <select class="select" style="width:150px" data-f="status"><option value="">Any status</option>${['success', 'error', 'running', 'waiting', 'blocked', 'rejected', 'approved', 'info', 'warning'].map((s) => `<option ${f.status === s ? 'selected' : ''}>${s}</option>`).join('')}</select>
        <div class="input-icon grow" style="min-width:200px">${icon('search')}<input class="input" data-f="q" placeholder="Filter messages, tools, scripts" value="${esc(f.q)}"></div>
        <span class="small muted">${rows.length} events</span>
      </div>
      <div class="card">${activityTable(rows.slice(0, limit), empById)}</div>
      ${rows.length > limit ? '<div class="row mt-16" style="justify-content:center"><button class="btn" id="more">Show more</button></div>' : ''}`;
    bindActivityRows(page, rows.slice(0, limit));
    page.querySelectorAll('[data-f]').forEach((i) => i.addEventListener(i.tagName === 'INPUT' ? 'change' : 'change', () => { f[i.dataset.f] = i.value; render(); }));
    page.querySelector('#more')?.addEventListener('click', () => { limit += 200; render(); });
    page.querySelector('#export').onclick = () => download(`workforge-activity-${Date.now()}.json`, JSON.stringify(rows, null, 2));
    refreshIcons();
  };
  ctx.watch(['activity'], render, 800);
  await render();
}
